# See: https://manski.net/2016/09/vagrant-multi-machine-tutorial/
# for information about machine names on private network
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  # This provision is common for both VMs
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y
    sudo apt-get install -y iputils-ping avahi-daemon libnss-mdns unzip \
        openjdk-17-jdk-headless
    # ifconfig
  SHELL

  #============
  # Configurations specific to the database VM
  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/bionic64"
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.56.11"

    # We want to access H2 console from the host using port 8082
    # We want to connect to the H2 server using port 9092
    db.vm.network "forwarded_port", guest: 8082, host: 8082
    db.vm.network "forwarded_port", guest: 9092, host: 9092

    # We need to download H2
    db.vm.provision "shell", inline: <<-SHELL
      wget https://repo1.maven.org/maven2/com/h2database/h2/1.4.200/h2-1.4.200.jar
    SHELL

    # The following provision shell will run ALWAYS so that we can execute the H2 server process
    # This could be done in a different way, for instance, setting H2 as a service
    db.vm.provision "shell", :run => 'always', inline: <<-SHELL
      java -cp ./h2*.jar org.h2.tools.Server -web -webAllowOthers -tcp -tcpAllowOthers -ifNotExists > ~/out.txt &
    SHELL
  end

  #============
  # Configurations specific to the webserver VM

  #Name of VM
  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/bionic64"
    web.vm.hostname = "web"
    #IP address of VM
    web.vm.network "private_network", ip: "192.168.56.10"

    # We set more RAM memory for this VM
    web.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end

    # We want to access Tomcat from the host using port 8080
    web.vm.network "forwarded_port", guest: 8080, host: 8080

    web.vm.provision "shell", inline: <<-SHELL, privileged: true
      # Use set -e command to exit if any command fails
      set -e

      #Install required items like specified in CA3/Part1

      #Install Git
      sudo apt install -y git

      #Install Gradle 8.6
      wget https://services.gradle.org/distributions/gradle-8.6-bin.zip
      sudo mkdir /opt/gradle
      sudo unzip -d /opt/gradle gradle-8.6-bin.zip
      echo "export GRADLE_HOME=/opt/gradle/gradle-8.6" >> ~/.bashrc
      echo "export PATH=$PATH:$GRADLE_HOME/bin" >> ~/.bashrc
      source ~/.bashrc

      #Clone repository, go to project root and change permissions of gradle wrapper
      git clone https://github.com/sepsilva/devops-23-24-PSM-1231869
      cd devops-23-24-PSM-1231869/CA2/Part2/react-and-spring-data-rest-basic
      chmod u+x gradlew

      #Build the project and run it
      ./gradlew clean build
      nohup ./gradlew bootRun > /home/vagrant/spring-boot-app.log 2>&1 &

    SHELL
  end
end
